### ISSUE TITLE
MPI run on initram.sh

### ISSUE THREAD

**Issue by lucypham951** [Tsjerk/Backward#9]
I think the logic was off: (initram.sh line 447-452 and 365-370)

**if $MPI
then
    NT=
else
    NT="-nt $NP"
fi**

I guess it should be:

**if $MPI
then
    NT="-nt $NP"
else
    NT=
fi**

**Comment by Tsjerk** [comment]
No, the -nt parameter is for the number of threads. When running with MPI this bit of code says to leave it up to MPI and run on full nodes (-nt defaults to all cores). This doesn't support complex schemes, and could be improved, but the revenue of that is small/modest.
